#!/usr/bin/env zsh

spechelp() {
    echo "------ special alias help ------"
    echo "netkill ------ Restart NetworkManager and Strongswan"
    echo "treehere ----- Run the tree command and format the output as a Markdown list  -- Argument: files to exclude 'here|and here'"
    echo "codecount ---- Count the lines of code in a directory     -- Argument: file type to include"
    echo "pls ---------- sudo"
    echo "shit --------- run previous command as sudo"
    echo "dotties ------ git alias for adding files to my dotties repository"
    echo "audio -------- restart pipewire and pipewire-pulse"
    echo "cpus --------- list processes using CPU"
    echo "fzff --------- fzf with bat"
}


# Restart network manager and strongswan
alias netkill="echo 'restarting NetworkManager..\n' && sudo systemctl restart NetworkManager && echo 'restarting Strongswan ..' && sudo systemctl restart strongswan"


# Run the tree command and format the output as a Markdown list  -- Argument: files to exclude 'here|and here'
function treehere() {
    # Run the tree command and format the output as a Markdown list
    tree=$(tree -tf --noreport -I "*~|"${1}"" --charset ascii . |
           sed -e 's/| \+/  /g' -e 's/[|`]-\+/ */g' -e 's:\(* \)\(\(.*/\)\([^/]\+\)\):\1[\4](\2):g')

    # Print the Markdown-formatted tree
    printf "<!-- markdownlint-disable MD001 MD007 -->\n\n# Project tree\n\n\`\`\` bash\ntreehere \"$1\"\n\`\`\`\n\n${tree}" > tree.md
}

function codecount() {
    # Count the lines of code in a directory
    find . -name "*.${1}" -type f -exec cat {} + | wc -l
    # codecount java html
    # find . -type f \( -name "*.${1}" $(printf -- '-o -name "*.%s" ' "${@:2}") \) -exec cat {} + | wc -l
}


alias shit='sudo $(history -p \!\!)'
alias pls='sudo'


# youtube downloader
function ytdl() {
    python3 -m pip install -U yt-dlp
    yt-dlp  -P ~/Documents/ytdl/ "$1"
}

# update git config
# dotties add nvim
# dotties commit -m 'nvim dot files added'
# dotties push -u origin main
alias dotties='/usr/bin/git --git-dir=/mnt/work/gh/aa/dotties --work-tree=$HOME'

alias audio='systemctl --user restart pipewire pipewire-pulse'

alias cpus='ps -eo pcpu,pid,user,args | tail -n +2 | sort -k1 -r -n | head -10'

alias fzff="fzf --preview 'bat --color=always {}' --preview-window '~3'"

# use fzf to find dirs only
# TODO this is awesome but has output on shell startup
#alias fzfdir="cd $(find . -type d -print | fzf)"
#
