#!/usr/bin/env zsh

navhelp() {
    echo "------ navigation ------"
    echo "..            cd .."
    echo "...           cd ../.."
    echo "....          cd ../../.."
    echo ".....         cd ../../../.."
    echo "cl            clear"
    echo
    echo "------ fedora WS important dirs ------"
    echo "balias        Open bash alias in neovim"
    echo "gh            local github dir"
    echo "aa            local aa github dir"
    echo "kestra        local kestra github"
    echo "ppd --------- local outdexing github"
    echo 
    echo "------ Programs ------"
    echo "r / ra ------ ranger"
    echo "d ----------- docker"
    echo "na ---------- open nautilus in current dir"
    echo "co ---------- open in VS code in current dir"
    echo "awsws ------- AWS workspace flatpak"
    echo "notes ------- Obsidian notes flatpak"
    echo
    echo "------ Work ------"
    echo "gh ---------- Github main dir"
    echo "aa ---------- aa Github dir"
    echo "kestra ------ kestra work dir"
    echo "kgh --------- kestra Github dir"
}


#=================================================#
##########---------- nav help  ----------##########
#=================================================#
#---------- General ----------#

alias ll="ls -lrt"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias cl="clear"


#-------- aws dev box -------#
alias ggit="cd /c/Users/andrew/Documents/GitHub"
alias bbalias="cd /c/Users/andrew/Documents/k3-GitHub/bash-alias"
alias ccharts="cd /c/Users/andrew/Documents/GitHub/infrastructure/kube/charts"
alias iimgs="cd /c/Users/andrew/Documents/GitHub/infrastructure/images"


#-------- fedora WS -------#
# Bash Alias's (here)
alias balias="cd /mnt/work/gh/aa/bash-alias && nvim ."

# work dirs
alias gh="cd "${WERK}"/gh"
alias aa="cd "${WERK}"/gh/aa"
alias kes="cd "${WERK}"/gh/kestra"
alias cash="cd "${WERK}"/gh/aa/cashflo"
alias ppd="cd "${WERK}"/gh/outdexing"


#=================================================#
##########------ Program shortcuts ------##########
#=================================================#
# ranger
alias r=". ranger"
alias ra="ranger"

# docker
alias d='docker'

# NeoVim
alias v='nvim'
alias vv='nvim .'

# Nautilus
alias na="nautilus . &"

# VS code here
alias co="code ."

# Obsidian Notes 
alias notes="flatpak run md.obsidian.Obsidian </dev/null &>/dev/null &"

# AWS workspace
alias awsws="flatpak run com.amazon.Workspaces </dev/null &>/dev/null &"

# Teams
alias teams="flatpak run --socket=wayland org.chromium.Chromium --app=https://teams.microsoft.com/"

# hyprland conf
alias hypr='cd ~/.config/hypr && nvim .'
