#!/usr/bin/env zsh

#=================================================#
##########--------- docker help ---------##########
#=================================================#

dockerhelp() {
    echo "------ general ------"
    echo "d ------------ docker"
    echo "dcu ---------- docker compose up"
    echo "dcd ---------- docker compose down"
    echo
}

alias d="docker"
alias dcu="d compose up"
alias dcd="d compose down"

alias devup="cd /mnt/work/gh/aa/devcontainer-templates/kestra && docker-compose -f docker-compose.yaml up"



alias cleanimg='d rmi -f $(d images -q -f "dangling=true")'

alias dstopall='d stop $(d ps -q)'


# Some stuff that is useful for working with a single container
alias dlo='d logs $(d ps -q)'