#!/usr/bin/env zsh

stockshelp() {
    echo "------ stocks alias help ------"
    echo "ticker ------- Edit the ticker config file"
    echo "stocks ------- Run stock ticker"
}


alias ticker='nvim /mnt/work/gh/aa/stocks/ticker.yaml'
alias stocks='docker run -it --rm -v /mnt/work/gh/aa/stocks/ticker.yaml:/.ticker.yaml  achannarasappa/ticker'
